export const products = [
  {
    id: 'table-basse-vert',
    kind: 'basse',
    kindLabel: 'Table basse',
    color: 'vert',
    colorLabel: 'Vert feuille',
    image: 'assets/photo-3.webp',
    alt: 'Table basse Écrin des Nuages, verre feuille de sauge et structure vert feuille',
    gallery: [
      'assets/photo-3.webp',
      'assets/photo-11.webp',
      'assets/photo-10.webp',
      'assets/photo-7.webp',
      'assets/photo-8.webp',
      'assets/photo-9.webp',
      'assets/photo-4.webp',
      'assets/photo-5.webp',
      'assets/photo-6.webp',
      'assets/photo-15.webp',
      'assets/photo-14.webp',
      'assets/photo-13.webp'
    ],
    galleryAlt: [
      'Table basse vert feuille',
      'Détail du plateau et d’un piétement de la table basse',
      'Courbe du plateau et bord du verre de la table basse',
      'Détail de la tranche et du piétement vert de la table basse',
      'Détail de l’assemblage du verre et du bois vert',
      'Percements et attaches du verre de la table basse',
      'Table basse et table haute devant la façade des Tours Nuages',
      'Les deux tables en dialogue avec les verres de la façade',
      'Les tables à l’échelle de la façade des Tours Nuages',
      'Deux tables sous les fenêtres feuille de sauge',
      'Piètements de la table haute et de la table basse',
      'Jonction entre le verre et la structure des deux tables'
    ],
    format: '1 verre',
    description: 'Une table basse qui révèle le contour organique du verre récupéré. Chaque pièce compose avec les marques et les nuances de son fragment architectural.',
    dimensions: 'L 129,7 × l 110,9 × h 40,2 cm',
    material: 'Verre trempé récupéré et structure en bois'
  },
  {
    id: 'table-basse-bleu',
    kind: 'basse',
    kindLabel: 'Table basse',
    color: 'bleu',
    colorLabel: 'Bleu ciel',
    format: '1 verre',
    image: 'assets/nuage-render-000.webp',
    alt: 'Vue de collection de la table basse Écrin des Nuages en teinte bleu ciel',
    gallery: ['assets/nuage-render-000.webp'],
    galleryAlt: ['Vue de collection de la table basse bleu ciel, un verre'],
    caption: 'Vue de collection',
    description: 'La silhouette de la table basse se décline en bleu ciel. Le visuel est une vue de collection.',
    dimensions: 'L 129,7 × l 110,9 × h 40,2 cm',
    material: 'Verre trempé récupéré et structure en bois'
  },
  {
    id: 'table-basse-bleu-2',
    kind: 'basse',
    kindLabel: 'Table basse',
    color: 'bleu',
    colorLabel: 'Bleu ciel',
    format: '2 verres',
    image: 'assets/nuage-render-002.webp',
    alt: 'Vue de collection d’une table basse à deux verres, bleu ciel',
    gallery: ['assets/nuage-render-002.webp'],
    galleryAlt: ['Vue de collection de la table basse bleu ciel, deux verres'],
    caption: 'Vue de collection',
    description: 'Assemblage dessiné de deux verres, en table basse bleu ciel. Le visuel est une vue de collection.'
  },
  {
    id: 'table-haute-bleu',
    kind: 'haute',
    kindLabel: 'Table haute',
    color: 'bleu',
    colorLabel: 'Bleu ciel',
    image: 'assets/photo-2.webp',
    alt: 'Table haute Écrin des Nuages en bleu ciel, verre feuille de sauge et structure en bois',
    gallery: [
      'assets/photo-2.webp',
      'assets/photo-12.webp',
      'assets/photo-1.webp',
      'assets/photo-4.webp',
      'assets/photo-5.webp',
      'assets/photo-6.webp',
      'assets/photo-15.webp',
      'assets/photo-14.webp',
      'assets/photo-13.webp'
    ],
    galleryAlt: [
      'Table haute bleu ciel',
      'Détail de la table haute et de son verre',
      'Table haute lors d’une rencontre devant les Tours Nuages',
      'Table basse et table haute devant la façade des Tours Nuages',
      'Les deux tables en dialogue avec les verres de la façade',
      'Les tables à l’échelle de la façade des Tours Nuages',
      'Deux tables sous les fenêtres feuille de sauge',
      'Piètements de la table haute et de la table basse',
      'Jonction entre le verre et la structure des deux tables'
    ],
    format: '1 verre',
    description: 'La première table autoproduite, présentée à Paris Design Week Factory en 2025. Sa structure accueille le verre à fleur et reprend le dessin des anciennes fixations.',
    dimensions: 'L 124 × l 113 × h 75 cm',
    material: 'Bois de hêtre huilé teinté bleu ciel, verre trempé et platines aluminium'
  },
  {
    id: 'table-haute-vert',
    kind: 'haute',
    kindLabel: 'Table haute',
    color: 'vert',
    colorLabel: 'Vert feuille',
    format: '1 verre',
    image: 'assets/nuage-render-001.webp',
    alt: 'Vue de collection de la table haute Écrin des Nuages en teinte vert feuille',
    gallery: ['assets/nuage-render-001.webp'],
    galleryAlt: ['Vue de collection de la table haute vert feuille, un verre'],
    caption: 'Vue de collection',
    description: 'La table haute reprend le dessin du verre « feuille de sauge ». Le visuel est une vue de collection.',
    dimensions: 'L 124 × l 113 × h 75 cm'
  },
  {
    id: 'table-haute-bleu-2',
    kind: 'haute',
    kindLabel: 'Table haute',
    color: 'bleu',
    colorLabel: 'Bleu ciel',
    format: '2 verres',
    image: 'assets/nuage-render-003.webp',
    alt: 'Vue de collection d’une table haute à deux verres, bleu ciel',
    gallery: ['assets/nuage-render-003.webp'],
    galleryAlt: ['Vue de collection de la table haute bleu ciel, deux verres'],
    caption: 'Vue de collection',
    description: 'Assemblage dessiné de deux verres, en table haute bleu ciel. Le visuel est une vue de collection.'
  },
  {
    id: 'table-haute-vert-2',
    kind: 'haute',
    kindLabel: 'Table haute',
    color: 'vert',
    colorLabel: 'Vert feuille',
    format: '2 verres',
    image: 'assets/nuage-render-004.webp',
    alt: 'Vue de collection d’une table haute à deux verres, vert feuille',
    gallery: ['assets/nuage-render-004.webp'],
    galleryAlt: ['Vue de collection de la table haute vert feuille, deux verres'],
    caption: 'Vue de collection',
    description: 'Assemblage dessiné de deux verres, en table haute vert feuille. Le visuel est une vue de collection.'
  },
  {
    id: 'table-haute-bleu-4',
    kind: 'haute',
    kindLabel: 'Table haute',
    color: 'bleu',
    colorLabel: 'Bleu ciel',
    format: '4 verres',
    image: 'assets/nuage-render-005.webp',
    alt: 'Vue de collection d’une table haute à quatre verres, bleu ciel',
    gallery: ['assets/nuage-render-005.webp'],
    galleryAlt: ['Vue de collection de la table haute bleu ciel, quatre verres'],
    caption: 'Vue de collection',
    description: 'Assemblage dessiné de quatre verres, en table haute bleu ciel. Le visuel est une vue de collection.'
  }
];
